# permissions for end users to edit actinodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: actinode-editor-role
rules:
- apiGroups:
  - apis.my.domain
  resources:
  - actinodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apis.my.domain
  resources:
  - actinodes/status
  verbs:
  - get
